services:
  pg:
    image: postgres:latest
    container_name: pg
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: mypassword
      POSTGRES_DB: launchpad
    ports:
      - "5432:5432"
    volumes:
      - pg_data:/var/lib/postgresql/data
    networks:
      - launchpad

  server:
    container_name: server
    image: ghcr.io/owaisad/launchpad/server:latest
    restart: always
    env_file:
      - .env
    environment:
      PORT: 8080
      DATABASE_URL: postgresql://user:mypassword@pg:5432/launchpad
      REDIS_URL: redis://default:${REDIS_PASSWORD}@redis:6379
      NODE_ENV: production
      CLERK_PUBLISHABLE_KEY: ${CLERK_PUBLISHABLE_KEY}
      CLERK_SECRET_KEY: ${CLERK_SECRET_KEY}
      CLERK_WEBHOOK_SIGNING_SECRET: ${CLERK_WEBHOOK_SIGNING_SECRET}
      GITHUB_TOKEN: ${GITHUB_TOKEN}
    volumes:
      - ./docker-data/server:/usr/src/app
    networks:
      - launchpad
      - traefik_default
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.api.rule=Host(`api.launchpad.sportia.dk`)"
      - "traefik.http.routers.api.entrypoints=web,websecure"
      - "traefik.http.routers.api.tls.certresolver=letsencrypt"
      - "traefik.http.services.api.loadbalancer.server.port=8080"

  client:
    container_name: client
    image: ghcr.io/owaisad/launchpad/client:latest
    restart: always
    environment:
      NODE_ENV: production
      VITE_CLERK_FRONTEND_API: ${VITE_CLERK_FRONTEND_API}
      VITE_API_URL: ${VITE_API_URL}
    depends_on:
      - server
    volumes:
      - ./docker-data/client:/usr/src/app
    networks:
      - launchpad
      - traefik_default
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.client.rule=Host(`launchpad.sportia.dk`)"
      - "traefik.http.routers.client.entrypoints=web,websecure"
      - "traefik.http.routers.client.tls.certresolver=letsencrypt"
      - "traefik.http.services.client.loadbalancer.server.port=3000"

  watchtower:
    container_name: watchtower
    image: containrrr/watchtower:latest
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - /root/.docker/config.json:/config.json
    command: --interval 30
    restart: always
    networks:
      - launchpad

volumes:
  docker-data:
  pg_data:

networks:
  launchpad:
    driver: bridge
  traefik_default:
    external: true
