services:
  server:
    container_name: server-{{PROJECT_SLUG}}
    image: ghcr.io/owaisad/lp-{{PROJECT_SLUG}}/server:latest
    restart: always
    ports:
      - "{{API_PORT}}:8080"
    environment:
      NODE_ENV: production
      DATABASE_URL: postgresql://user:mypassword@pg:5432/{{PROJECT_SLUG}}
    networks:
      - launchpad

  client:
    container_name: client-{{PROJECT_SLUG}}
    image: ghcr.io/owaisad/lp-{{PROJECT_SLUG}}/client:latest
    restart: always
    ports:
      - "{{CLIENT_PORT}}:3001"
    depends_on:
      - server
    networks:
      - launchpad

networks:
  launchpad:
    external: true
