services:
  server:
    container_name: server-{{PROJECT_SLUG}}
    image: ghcr.io/owaisad/lp-{{PROJECT_SLUG}}/server:latest
    restart: always
    networks:
      - launchpad-{{PROJECT_SLUG}}

  client:
    container_name: client-{{PROJECT_SLUG}}
    image: ghcr.io/owaisad/lp-{{PROJECT_SLUG}}/client:latest
    restart: always
    depends_on:
      - server
    networks:
      - launchpad-{{PROJECT_SLUG}}

networks:
  launchpad-{{PROJECT_SLUG}}:
    driver: bridge
