name: Deploying LaunchPad Client and Server

on:
  push:
    branches:
      - master

jobs:
  buildAndPush:
    permissions: write-all
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setting up Node.js environment
        uses: ./.github/workflows/shared

      - name: Build the application
        run: npm run build

      - name: Semantic Release
        id: semantic
        run: npx semantic-release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      # Only proceed if a release was created
      - name: Extract new version
        if: steps.semantic.outputs.new-release-published == 'true'
        run: echo "RELEASE_VERSION=${{ steps.semantic.outputs.release-version }}" >> $GITHUB_ENV

      - name: Fail if no new release
        if: steps.semantic.outputs.new-release-published != 'true'
        run: |
          echo "No new release published. Skipping Docker build and push."
          exit 0

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }} # Use the GitHub actor (the user triggering the action)
          password: ${{ secrets.GITHUB_TOKEN }} # Use the provided GitHub token

      - name: Build & push client image (once, multiple tags)
        run: |
          IMAGE_NAME="ghcr.io/$(echo "${{ github.repository }}" | tr '[:upper:]' '[:lower:]')/client"

          docker build -t $IMAGE_NAME:${{ github.sha }} ./client
          docker tag $IMAGE_NAME:${{ github.sha }} $IMAGE_NAME:latest
          docker push $IMAGE_NAME:${{ github.sha }}
          docker push $IMAGE_NAME:latest

      - name: Build & push server image (once, multiple tags)
        run: |
          IMAGE_NAME="ghcr.io/$(echo "${{ github.repository }}" | tr '[:upper:]' '[:lower:]')/server"

          docker build -t $IMAGE_NAME:${{ github.sha }} ./server
          docker tag $IMAGE_NAME:${{ github.sha }} $IMAGE_NAME:latest
          docker push $IMAGE_NAME:${{ github.sha }}
          docker push $IMAGE_NAME:latest
